"use strict";
(function(){
const q=id=>document.getElementById(id),money=n=>"₦"+Math.round(n).toLocaleString();
const JOBS=[{n:"Shop Assistant",pay:3000,skill:"hustle",lvl:1},{n:"Junior Developer",pay:7500,skill:"coding",lvl:2},{n:"Bank Officer",pay:6500,skill:"charisma",lvl:2},{n:"Project Manager",pay:16000,skill:"charisma",lvl:5},{n:"Senior Developer",pay:22000,skill:"coding",lvl:6}];
const PLACES=[{n:"Nsukka",fare:0},{n:"Ogbete",fare:2200},{n:"New Haven",fare:2500},{n:"Independence Layout",fare:2800},{n:"Nike",fare:3000}];
const HOMES=[{n:"Campus Lodge",rent:2500,deposit:0},{n:"Nsukka Self-contain",rent:6500,deposit:26000},{n:"Enugu Flat",rent:24000,deposit:96000},{n:"GRA Apartment",rent:85000,deposit:340000}];
const DISTRICTS=[
{tag:"UNN / NSUKKA",venues:[["🎓","UNN Campus","Study, exams & campus life","school"],["🍲","Okpa Spot","Eat and recover hunger","eat"],["🏠","Campus Lodge","Rest at home","sleep"]]},
{tag:"OGBETE",venues:[["🛍️","Ogbete Market","Hustles and business","business"],["🏦","Bank Row","Find career opportunities","work"],["🍛","Food Joint","Grab a meal","eat"]]},
{tag:"NEW HAVEN",venues:[["💻","Tech Hub","Coding and tech careers","work"],["☕","Cafe","Meet people","people"],["🏢","Apartments","Housing options","assets"]]},
{tag:"INDEPENDENCE LAYOUT",venues:[["🏢","Business District","Build your company","business"],["🍽️","Restaurant","Eat and socialise","eat"],["🚗","Auto Dealer","Buy a vehicle","assets"]]},
{tag:"NIKE",venues:[["🌴","Nike Lake","Relax and have fun","fun"],["🏘️","Residential Area","View homes","assets"],["🤝","Hangout","Meet people","people"]]}
];
const BUSINESSES=[{n:"Okpa Stand",cost:45000,income:3500},{n:"Design Studio",cost:180000,income:12000},{n:"Software Agency",cost:650000,income:35000}];
function newState(){return{name:"",trait:"hustler",cash:30000,debt:0,day:1,week:1,place:0,home:0,job:-1,semester:1,graduate:false,rep:0,car:false,needs:{hunger:85,energy:90,fun:70,social:65},skills:{hustle:1,coding:1,charisma:1,academics:1},businesses:[],friends:{Ada:10,Emeka:15,Chisom:8},log:["Your story begins in Nsukka."],tab:"life"}}
let state=newState();try{const old=localStorage.getItem("enuguLifeV4");if(old)state=Object.assign(newState(),JSON.parse(old))}catch(e){state=newState()}
let selectedTrait="hustler";
function persist(){localStorage.setItem("enuguLifeV4",JSON.stringify(state))}
function note(t){state.log.unshift("Day "+state.day+" — "+t);state.log=state.log.slice(0,8)}
function toast(t){q("toast").textContent=t;q("toast").classList.add("show");setTimeout(()=>q("toast").classList.remove("show"),1400)}
function pay(n){if(state.cash<n){toast("Not enough cash.");return false}state.cash-=n;return true}
function nextDay(){state.day++;Object.keys(state.needs).forEach(k=>state.needs[k]=Math.max(0,state.needs[k]-5));if(state.day%7===0){state.week++;let inc=state.businesses.reduce((a,i)=>a+BUSINESSES[i].income,0);state.cash+=inc-HOMES[state.home].rent;note("Weekly income "+money(inc)+" • rent "+money(HOMES[state.home].rent));if(state.cash<0){state.debt+=Math.abs(state.cash);state.cash=0}}}
function saveRender(){persist();render()}
function world(){let d=DISTRICTS[state.place];let v=d.venues;return '<section class="card world wide"><div class="sun"></div><div class="district-badge">📍 '+d.tag+'</div><div class="world-hint">Tap a building or person</div>'+v.map((x,i)=>'<button class="world-building wb'+(i+1)+'" onclick="visitVenue('+i+')"><span class="structure"></span><strong>'+x[0]+' '+x[1]+'</strong></button>').join("")+'<div class="world-player"><div class="avatar"></div><div class="torso"></div><strong>'+state.name+'</strong></div><button class="world-npc wn1" onclick="talk(\'Ada\')"><div class="avatar"></div><div class="torso" style="background:#f1a7c0"></div><strong>Ada</strong></button><button class="world-npc wn2" onclick="talk(\'Emeka\')"><div class="avatar"></div><div class="torso" style="background:#79b8ec"></div><strong>Emeka</strong></button><div class="vehicle">'+(state.car?"🚗":"🛺")+'</div></section>'}
function row(a,b,c){return '<div class="row"><div><b>'+a+'</b><p>'+b+'</p></div>'+c+'</div>'}
function card(t,b,wide){return '<section class="card '+(wide?"wide":"")+'"><h3>'+t+'</h3>'+b+'</section>'}
window.visitVenue=function(i){let v=DISTRICTS[state.place].venues[i],a=v[3];if(a==="eat"){doAction("eat");return}if(a==="sleep"){doAction("sleep");return}if(a==="fun"){doAction("fun");return}state.tab=a;note("Visited "+v[1]+".");saveRender()};
window.doAction=function(a){if(a==="eat"){if(!pay(900))return;state.needs.hunger=Math.min(100,state.needs.hunger+35);note("Ate a good meal.")}else if(a==="sleep"){state.needs.energy=100;note("Slept and recovered.")}else if(a==="gig"){let p=2200+state.skills.hustle*700+(state.trait==="hustler"?1000:0);state.cash+=p;state.skills.hustle=Math.min(10,state.skills.hustle+.2);note("Side hustle paid "+money(p))}else if(a==="fun"){if(!pay(2000))return;state.needs.fun=Math.min(100,state.needs.fun+35);state.needs.social=Math.min(100,state.needs.social+20);note("Went out with friends.")}nextDay();saveRender()};
window.applyJob=function(i){let j=JOBS[i];if(state.skills[j.skill]<j.lvl){toast(j.skill+" level "+j.lvl+" required.");return}state.job=i;note("Got a job as "+j.n+".");saveRender()};
window.workShift=function(){if(state.job<0){toast("Get a job first.");return}if(state.needs.energy<20){toast("You need rest.");return}let j=JOBS[state.job];state.cash+=j.pay;state.needs.energy=Math.max(0,state.needs.energy-20);state.skills[j.skill]=Math.min(10,state.skills[j.skill]+.2);state.rep++;note("Worked as "+j.n+" and earned "+money(j.pay));nextDay();saveRender()};
window.train=function(k,c){if(!pay(c))return;let bonus=(state.trait==="techie"&&k==="coding")||(state.trait==="book"&&k==="academics")?.5:0;state.skills[k]=Math.min(10,state.skills[k]+1+bonus);note("Improved "+k+".");nextDay();saveRender()};
window.exam=function(){if(state.graduate){toast("Already graduated 🎓");return}if(state.skills.academics<state.semester){toast("Study more first.");return}let c=12000+state.semester*3000;if(!pay(c))return;state.semester++;if(state.semester>8){state.semester=8;state.graduate=true;note("Graduated from UNN 🎓")}else note("Passed exams. Semester "+state.semester);nextDay();saveRender()};
window.travel=function(i){let fare=state.car?Math.floor(PLACES[i].fare*.4):PLACES[i].fare;if(!pay(fare))return;state.place=i;note("Travelled to "+PLACES[i].n+".");nextDay();saveRender()};
window.startBusiness=function(i){if(state.businesses.includes(i)){toast("Already owned.");return}if(!pay(BUSINESSES[i].cost))return;state.businesses.push(i);state.rep+=2;note("Opened "+BUSINESSES[i].n+".");saveRender()};
window.moveHome=function(i){if(!pay(HOMES[i].deposit))return;state.home=i;note("Moved into "+HOMES[i].n+".");saveRender()};
window.buyCar=function(){if(state.car){toast("You already own a car.");return}if(!pay(6500000))return;state.car=true;state.rep+=5;note("Bought a used Corolla.");saveRender()};
window.talk=function(n){if(!pay(1000))return;state.friends[n]=Math.min(100,state.friends[n]+10+(state.trait==="social"?5:0));state.needs.social=Math.min(100,state.needs.social+20);note("Spent time with "+n+".");nextDay();saveRender()};
function render(){
q("greeting").textContent="Nnoo, "+state.name+" 👋🏾";q("meta").textContent="Day "+state.day+" • Week "+state.week+" • "+PLACES[state.place].n;q("cash").textContent=money(state.cash);q("footerText").textContent=HOMES[state.home].n+" • Reputation "+state.rep;
q("needs").innerHTML=Object.entries(state.needs).map(([k,v])=>'<div class="need">'+k.toUpperCase()+' <b>'+Math.round(v)+'</b><div class="bar"><i style="width:'+v+'%"></i></div></div>').join("");
const tabs=[["life","🏠 Life"],["work","💼 Work"],["school","🎓 School"],["business","🏪 Business"],["city","🗺️ City"],["people","👥 People"],["assets","🚗 Assets"]];
q("nav").innerHTML=tabs.map(t=>'<button data-tab="'+t[0]+'" class="'+(state.tab===t[0]?"active":"")+'">'+t[1]+'</button>').join("");
q("nav").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{state.tab=b.dataset.tab;saveRender()}));
let html='<div class="grid">';
if(state.tab==="life"){let venues=DISTRICTS[state.place].venues.map((v,i)=>'<button class="venue" onclick="visitVenue('+i+')"><span class="icon">'+v[0]+'</span><b>'+v[1]+'</b><span>'+v[2]+'</span></button>').join("");html+=world()+card("Explore "+PLACES[state.place].n,'<div class="venue-grid">'+venues+'</div>',true)+card("Today",'<p>'+state.log[0]+'</p><div class="actions"><button onclick="doAction(\'eat\')">🍲 Eat '+money(900)+'</button><button onclick="doAction(\'sleep\')">😴 Sleep</button><button onclick="doAction(\'gig\')">💸 Side hustle</button><button onclick="doAction(\'fun\')">🎉 Go out</button></div>',true)+card("Skills",Object.entries(state.skills).map(x=>row(x[0],"Level "+x[1].toFixed(1),"")).join(""))+card("Life log",state.log.map(x=>row(x,"","")).join(""))}
if(state.tab==="work"){html+=card("Career",'<p>'+(state.job<0?"You are unemployed.":JOBS[state.job].n)+'</p><button onclick="workShift()">Work a shift</button>',true)+card("Job market",JOBS.map((j,i)=>row(j.n,money(j.pay)+"/shift • "+j.skill+" Lv "+j.lvl,'<button onclick="applyJob('+i+')">Apply</button>')).join(""))}
if(state.tab==="school"){html+=card("UNN",'<h2>'+(state.graduate?"Graduate 🎓":"Semester "+state.semester+"/8")+'</h2><button onclick="exam()">Sit exams</button>',true)+card("Train",row("Study","Academics +1",'<button onclick="train(\'academics\',3500)">₦3,500</button>')+row("Coding","Coding +1",'<button onclick="train(\'coding\',12000)">₦12k</button>')+row("Networking","Charisma +1",'<button onclick="train(\'charisma\',6000)">₦6k</button>'))}
if(state.tab==="business"){html+=card("Businesses",state.businesses.length?state.businesses.map(i=>row(BUSINESSES[i].n,money(BUSINESSES[i].income)+"/week",'<span class="pill">OWNED</span>')).join(""):"<p>No business yet.</p>",true)+card("Start one",BUSINESSES.map((b,i)=>row(b.n,money(b.cost)+" • "+money(b.income)+"/week",'<button onclick="startBusiness('+i+')">Start</button>')).join(""))}
if(state.tab==="city"){html+=world()+card("Travel",'<div class="map">'+PLACES.map((p,i)=>'<button onclick="travel('+i+')" class="'+(state.place===i?"active":"")+'"><b>'+p.n+'</b><span>'+money(p.fare)+' fare</span></button>').join("")+'</div>',true)}
if(state.tab==="people"){html+=world()+card("People nearby",Object.entries(state.friends).map(([n,v])=>row(n,"Bond "+v+"/100",'<button onclick="talk(\''+n+'\')">Talk</button>')).join(""),true)}
if(state.tab==="assets"){html+=card("Housing",HOMES.map((h,i)=>row(h.n,money(h.rent)+"/week • "+money(h.deposit)+" deposit",state.home===i?'<span class="pill">HOME</span>':'<button onclick="moveHome('+i+')">Move</button>')).join(""))+card("Vehicle",state.car?row("Used Corolla","Travel discount",'<span class="pill">OWNED</span>'):row("Used Corolla",money(6500000),'<button onclick="buyCar()">Buy</button>'))}
q("view").innerHTML=html+"</div>"}
function enterGame(){q("onboarding").classList.add("hidden");q("game").classList.remove("hidden");render()}
q("traits").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{selectedTrait=b.dataset.trait;q("traits").querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}));
q("startButton").addEventListener("click",()=>{let name=q("nameInput").value.trim();if(!name){q("startError").textContent="Enter your name first.";return}state=newState();state.name=name;state.trait=selectedTrait;state.skills[{hustler:"hustle",techie:"coding",social:"charisma",book:"academics"}[selectedTrait]]++;persist();enterGame();toast("Welcome, "+name+"!")});
q("resetButton").addEventListener("click",()=>{if(confirm("Start a new life?")){localStorage.removeItem("enuguLifeV4");state=newState();q("game").classList.add("hidden");q("onboarding").classList.remove("hidden");q("nameInput").value=""}});
if(state.name)enterGame();
})();