"use strict";
(function(){
const q=id=>document.getElementById(id),money=n=>"₦"+Math.round(n).toLocaleString();
const JOBS=[{n:"Shop Assistant",pay:3000,skill:"hustle",lvl:1},{n:"Junior Developer",pay:7500,skill:"coding",lvl:2},{n:"Bank Officer",pay:6500,skill:"charisma",lvl:2},{n:"Project Manager",pay:16000,skill:"charisma",lvl:5},{n:"Senior Developer",pay:22000,skill:"coding",lvl:6}];
const PLACES=[
{n:"Nsukka / UNN",fare:0,x:7,y:8,icon:"🎓"},
{n:"GRA",fare:2300,x:34,y:13,icon:"🏡"},
{n:"Trans-Ekulu",fare:2600,x:57,y:8,icon:"🏘️"},
{n:"Abakpa Nike",fare:3000,x:76,y:20,icon:"🏪"},
{n:"Emene",fare:3600,x:88,y:31,icon:"✈️"},
{n:"New Haven",fare:2400,x:50,y:32,icon:"☕"},
{n:"Ogui / Asata",fare:2100,x:35,y:42,icon:"🏙️"},
{n:"Ogbete",fare:2200,x:27,y:53,icon:"🛍️"},
{n:"Independence Layout",fare:2800,x:58,y:50,icon:"🏛️"},
{n:"Thinkers Corner",fare:3100,x:76,y:43,icon:"💡"},
{n:"Uwani",fare:2500,x:38,y:67,icon:"🏠"},
{n:"Achara Layout",fare:2800,x:47,y:82,icon:"🏘️"},
{n:"Nike Lake",fare:3400,x:73,y:69,icon:"🌴"}
];
const HOMES=[{n:"Campus Lodge",rent:2500,deposit:0},{n:"Nsukka Self-contain",rent:6500,deposit:26000},{n:"Enugu Flat",rent:24000,deposit:96000},{n:"GRA Apartment",rent:85000,deposit:340000}];
const DISTRICTS=[
{tag:"UNN / NSUKKA",venues:[["🎓","UNN Campus","Study, exams & campus life","school"],["🍲","Okpa Spot","Eat and recover hunger","eat"],["🏠","Campus Lodge","Rest at home","sleep"]]},
{tag:"OGBETE",venues:[["🛍️","Ogbete Market","Hustles and business","business"],["🏦","Bank Row","Find career opportunities","work"],["🍛","Food Joint","Grab a meal","eat"]]},
{tag:"NEW HAVEN",venues:[["💻","Tech Hub","Coding and tech careers","work"],["☕","Cafe","Meet people","people"],["🏢","Apartments","Housing options","assets"]]},
{tag:"INDEPENDENCE LAYOUT",venues:[["🏢","Business District","Build your company","business"],["🍽️","Restaurant","Eat and socialise","eat"],["🚗","Auto Dealer","Buy a vehicle","assets"]]},
{tag:"NIKE",venues:[["🌴","Nike Lake","Relax and have fun","fun"],["🏘️","Residential Area","View homes","assets"],["🤝","Hangout","Meet people","people"]]}
];
const BUSINESSES=[{n:"Okpa Stand",cost:45000,income:3500},{n:"Design Studio",cost:180000,income:12000},{n:"Software Agency",cost:650000,income:35000}];
function newState(){return{name:"",trait:"hustler",cash:30000,debt:0,day:1,week:1,place:0,home:0,job:-1,semester:1,graduate:false,rep:0,car:false,px:48,py:70,needs:{hunger:85,energy:90,fun:70,social:65},skills:{hustle:1,coding:1,charisma:1,academics:1},businesses:[],friends:{Ada:10,Emeka:15,Chisom:8},log:["Your story begins in Nsukka."],tab:"home",interior:null}}
let state=newState();try{const old=localStorage.getItem("enuguLifeV4");if(old)state=Object.assign(newState(),JSON.parse(old))}catch(e){state=newState()}
let selectedTrait="hustler";
function persist(){localStorage.setItem("enuguLifeV4",JSON.stringify(state))}
function note(t){state.log.unshift("Day "+state.day+" — "+t);state.log=state.log.slice(0,8)}
function toast(t){q("toast").textContent=t;q("toast").classList.add("show");setTimeout(()=>q("toast").classList.remove("show"),1400)}
function pay(n){if(state.cash<n){toast("Not enough cash.");return false}state.cash-=n;return true}
function nextDay(){state.day++;Object.keys(state.needs).forEach(k=>state.needs[k]=Math.max(0,state.needs[k]-5));if(state.day%7===0){state.week++;let inc=state.businesses.reduce((a,i)=>a+BUSINESSES[i].income,0);state.cash+=inc-HOMES[state.home].rent;note("Weekly income "+money(inc)+" • rent "+money(HOMES[state.home].rent));if(state.cash<0){state.debt+=Math.abs(state.cash);state.cash=0}}}
function saveRender(){persist();render()}
function outfit(){return state.trait==="techie"?"tech":state.trait==="social"?"social":state.trait==="book"?"student":"hustler"}
function world(){let d=DISTRICTS[state.place],v=d.venues;return '<section class="gameworld wide"><div class="worldtop"><b>📍 '+d.tag+'</b><span>Tap anywhere to walk • tap a place to enter</span></div><div id="playfield" class="playfield district-'+state.place+'"><div class="road road-h"></div><div class="road road-v"></div><div class="crosswalk"></div><div class="tree t1">🌳</div><div class="tree t2">🌴</div><div class="tree t3">🌳</div>'+v.map((x,i)=>'<button class="map-building mb'+(i+1)+'" data-venue="'+i+'"><span class="roof"></span><span class="front"><i></i><i></i><em></em></span><strong>'+x[0]+' '+x[1]+'</strong></button>').join("")+'<button class="map-npc npc-a" data-person="Ada"><span>👩🏾</span><b>Ada</b></button><button class="map-npc npc-e" data-person="Emeka"><span>👨🏾</span><b>Emeka</b></button><button class="map-npc npc-c" data-person="Chisom"><span>🧑🏾</span><b>Chisom</b></button><div id="playerSprite" class="player-sprite '+outfit()+'" style="left:'+(state.px||48)+'%;top:'+(state.py||70)+'%"><span class="hair"></span><span class="face"></span><span class="shirt"></span><span class="legs"></span><b>'+state.name+'</b></div><div class="traffic">🛺</div></div></section>'}
function interior(){if(state.interior===null)return "";let v=DISTRICTS[state.place].venues[state.interior],label=v[3]==="eat"?"🍲 Buy meal":v[3]==="sleep"?"😴 Rest":v[3]==="fun"?"✨ Relax":"Continue →";return '<section class="roomscene wide"><div class="room-back"><div class="room-sign">'+v[0]+' '+v[1]+'</div><div class="room-window"></div><div class="room-counter"></div><div class="room-player '+outfit()+'"><span class="hair"></span><span class="face"></span><span class="shirt"></span><span class="legs"></span></div><div class="room-actions"><button onclick="venueAction()">'+label+'</button><button onclick="leaveVenue()">← Go outside</button></div></div></section>'}
function bindWorld(){let f=q("playfield");if(!f)return;f.addEventListener("click",e=>{if(e.target.closest(".map-building,.map-npc"))return;let r=f.getBoundingClientRect();state.px=Math.max(4,Math.min(92,(e.clientX-r.left)/r.width*100));state.py=Math.max(15,Math.min(84,(e.clientY-r.top)/r.height*100));persist();let p=q("playerSprite");p.style.left=state.px+"%";p.style.top=state.py+"%"});f.querySelectorAll(".map-building").forEach(x=>x.addEventListener("click",()=>enterVenue(Number(x.dataset.venue))));f.querySelectorAll(".map-npc").forEach(x=>x.addEventListener("click",()=>talk(x.dataset.person)))} 
function row(a,b,c){return '<div class="row"><div><b>'+a+'</b><p>'+b+'</p></div>'+c+'</div>'}
function card(t,b,wide){return '<section class="card '+(wide?"wide":"")+'"><h3>'+t+'</h3>'+b+'</section>'}
window.enterVenue=function(i){state.interior=i;note("Entered "+DISTRICTS[state.place].venues[i][1]+".");saveRender()};window.leaveVenue=function(){state.interior=null;saveRender()};window.venueAction=function(){let v=DISTRICTS[state.place].venues[state.interior],a=v[3];if(a==="eat"||a==="sleep"||a==="fun"){doAction(a);return}state.interior=null;state.tab=a;saveRender()};window.visitVenue=window.enterVenue;
window.doAction=function(a){if(a==="eat"){if(!pay(900))return;state.needs.hunger=Math.min(100,state.needs.hunger+35);note("Ate a good meal.")}else if(a==="sleep"){state.needs.energy=100;note("Slept and recovered.")}else if(a==="gig"){let p=2200+state.skills.hustle*700+(state.trait==="hustler"?1000:0);state.cash+=p;state.skills.hustle=Math.min(10,state.skills.hustle+.2);note("Side hustle paid "+money(p))}else if(a==="fun"){if(!pay(2000))return;state.needs.fun=Math.min(100,state.needs.fun+35);state.needs.social=Math.min(100,state.needs.social+20);note("Went out with friends.")}nextDay();saveRender()};
window.applyJob=function(i){let j=JOBS[i];if(state.skills[j.skill]<j.lvl){toast(j.skill+" level "+j.lvl+" required.");return}state.job=i;note("Got a job as "+j.n+".");saveRender()};
window.workShift=function(){if(state.job<0){toast("Get a job first.");return}if(state.needs.energy<20){toast("You need rest.");return}let j=JOBS[state.job];state.cash+=j.pay;state.needs.energy=Math.max(0,state.needs.energy-20);state.skills[j.skill]=Math.min(10,state.skills[j.skill]+.2);state.rep++;note("Worked as "+j.n+" and earned "+money(j.pay));nextDay();saveRender()};
window.train=function(k,c){if(!pay(c))return;let bonus=((state.trait==="techie"&&k==="coding")||(state.trait==="book"&&k==="academics"))?0.5:0;state.skills[k]=Math.min(10,state.skills[k]+1+bonus);note("Improved "+k+".");nextDay();saveRender()};
window.exam=function(){if(state.graduate){toast("Already graduated 🎓");return}if(state.skills.academics<state.semester){toast("Study more first.");return}let c=12000+state.semester*3000;if(!pay(c))return;state.semester++;if(state.semester>8){state.semester=8;state.graduate=true;note("Graduated from UNN 🎓")}else note("Passed exams. Semester "+state.semester);nextDay();saveRender()};
window.travel=function(i){state.interior=null;let fare=state.car?Math.floor(PLACES[i].fare*.4):PLACES[i].fare;if(!pay(fare))return;state.place=i;note("Travelled to "+PLACES[i].n+".");nextDay();saveRender()};
window.startBusiness=function(i){if(state.businesses.includes(i)){toast("Already owned.");return}if(!pay(BUSINESSES[i].cost))return;state.businesses.push(i);state.rep+=2;note("Opened "+BUSINESSES[i].n+".");saveRender()};
window.moveHome=function(i){if(!pay(HOMES[i].deposit))return;state.home=i;note("Moved into "+HOMES[i].n+".");saveRender()};
window.buyCar=function(){if(state.car){toast("You already own a car.");return}if(!pay(6500000))return;state.car=true;state.rep+=5;note("Bought a used Corolla.");saveRender()};
window.talk=function(n){if(!pay(1000))return;state.friends[n]=Math.min(100,state.friends[n]+10+(state.trait==="social"?5:0));state.needs.social=Math.min(100,state.needs.social+20);note("Spent time with "+n+".");nextDay();saveRender()};
function sim(){return '<div class="sim '+outfit()+'"><span class="simhair"></span><span class="simface"></span><span class="simbody"></span><span class="simlegs"></span></div>'}
function homeScene(){return '<section class="home3d-shell"><div class="home3d-title"><b>'+HOMES[state.home].n+'</b><span>Tap furniture to interact</span></div><div id="home3d"></div><div id="home3dLabels"></div></section>'}
function init3DHome(){let host=q("home3d");if(!host)return;let showError=m=>{if(host.isConnected&&!host.querySelector("canvas"))host.innerHTML='<div style="padding:24px;color:#16261c;font:600 14px system-ui">3D scene could not start.<br><small style="font-weight:400">'+m+'</small></div>'};let mount=()=>{if(window.EnuguCampus&&window.EnuguCampus.mountCampusLodge){window.EnuguCampus.mountCampusLodge(host,{sleep:()=>doAction("sleep"),eat:()=>doAction("eat"),coding:()=>train("coding",12000),fun:()=>doAction("fun"),wardrobe:()=>toast("Wardrobe customization coming next.")}).catch(e=>{console.error(e);showError(e.message||String(e))});return true}return false};if(mount())return;let ready=()=>{cleanup();if(!mount())showError("3D module loaded without lodge renderer.")},bad=()=>{cleanup();showError(window.__ENUGU_3D_ERROR__||"3D module failed to load.")},cleanup=()=>{window.removeEventListener("enugu-assets-ready",ready);window.removeEventListener("enugu-assets-error",bad)};window.addEventListener("enugu-assets-ready",ready,{once:true});window.addEventListener("enugu-assets-error",bad,{once:true});setTimeout(()=>{if(!host.isConnected||host.querySelector("canvas"))return;if(window.__ENUGU_3D_ERROR__)bad();else if(window.__ENUGU_3D_READY__)ready();else showError("Waiting for the 3D module timed out.")},5000)}
function initModelHome(host,model){let scene=new THREE.Scene();scene.background=new THREE.Color(0xb9c7bf);let w=host.clientWidth,h=host.clientHeight,cam=new THREE.PerspectiveCamera(38,w/h,.1,150);cam.position.set(7,6,9);cam.lookAt(0,1,0);let ren=new THREE.WebGLRenderer({antialias:true,powerPreference:"low-power"});ren.setPixelRatio(Math.min(devicePixelRatio,1.5));ren.setSize(w,h);ren.shadowMap.enabled=true;host.appendChild(ren.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x5d5547,2.1));let sun=new THREE.DirectionalLight(0xffe1b5,3);sun.position.set(-5,10,7);sun.castShadow=true;scene.add(sun);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(model);let actions={INT_SLEEP:"sleep",INT_EAT:"eat",INT_COMPUTER:"coding",INT_RELAX:"fun",INT_WARDROBE:"wardrobe",INT_EXIT:"exit"},targets=[];Object.keys(actions).forEach(n=>{let o=model.getObjectByName(n);if(o){o.userData.action=actions[n];targets.push(o)}});let ray=new THREE.Raycaster(),mouse=new THREE.Vector2();ren.domElement.addEventListener("pointerup",e=>{let r=ren.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,cam);let hit=ray.intersectObjects(targets,true)[0];if(!hit)return;let o=hit.object;while(o&&!o.userData.action)o=o.parent;if(!o)return;let a=o.userData.action;if(a==="coding")train("coding",12000);else if(a==="wardrobe")toast("Wardrobe customization coming next.");else if(a==="exit"){state.tab="map";saveRender()}else doAction(a)});function loop(){if(!host.isConnected)return;ren.render(scene,cam);requestAnimationFrame(loop)}loop()}
function initFallbackHome(host){host.innerHTML="";let scene=new THREE.Scene();scene.background=new THREE.Color(0xd7c9b4);let w=host.clientWidth,h=host.clientHeight,cam=new THREE.PerspectiveCamera(36,w/h,.1,100);cam.position.set(10,10,13);cam.lookAt(0,1,0);let ren=new THREE.WebGLRenderer({antialias:true,powerPreference:"low-power"});ren.setPixelRatio(Math.min(devicePixelRatio,1.5));ren.setSize(w,h);ren.shadowMap.enabled=true;host.appendChild(ren.domElement);scene.add(new THREE.HemisphereLight(0xfff7e7,0x715c48,2.4));let sun=new THREE.DirectionalLight(0xffe0aa,2.8);sun.position.set(-6,12,8);sun.castShadow=true;scene.add(sun);
let mats={floor:new THREE.MeshStandardMaterial({color:0x9b7556,roughness:.9}),wall:new THREE.MeshStandardMaterial({color:0xe7d8c0,roughness:1}),wood:new THREE.MeshStandardMaterial({color:0x6b4933}),dark:new THREE.MeshStandardMaterial({color:0x252b29}),white:new THREE.MeshStandardMaterial({color:0xe8e6dd}),green:new THREE.MeshStandardMaterial({color:0x47785b}),blue:new THREE.MeshStandardMaterial({color:0x6696a7}),bed:new THREE.MeshStandardMaterial({color:0xb9c8a4}),skin:new THREE.MeshStandardMaterial({color:0x70472f})};
function cube(x,y,z,sx,sy,sz,mat){let m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
cube(0,-.15,0,12,.3,9,mats.floor);cube(0,2.7,-4.4,12,5.5,.2,mats.wall);cube(-5.9,2.7,0,.2,5.5,9,mats.wall);
let rug=cube(.5,.03,.6,4,.05,3,new THREE.MeshStandardMaterial({color:0xb36b4c}));let bed=cube(-3.7,.55,-2.7,3.2,.65,2.1,mats.bed);cube(-3.7,.93,-3.55,3.2,.25,.35,mats.white);bed.userData.action="sleep";
let sofa=cube(2.7,.62,2.4,3.2,.75,1.15,mats.green);cube(2.7,1.18,2.85,3.2,.9,.28,mats.green);sofa.userData.action="fun";
let desk=cube(-3.7,.8,2.4,2.7,.18,1.1,mats.wood);cube(-4.7,.38,2.4,.16,.8,.16,mats.wood);cube(-2.7,.38,2.4,.16,.8,.16,mats.wood);let monitor=cube(-3.7,1.42,2.28,1.15,.72,.12,mats.dark);monitor.userData.action="coding";desk.userData.action="coding";
let kitchen=cube(3.9,.7,-3.55,3.2,1.4,.7,mats.white);kitchen.userData.action="eat";let fridge=cube(4.75,1.45,-3.5,1.05,2.9,.9,mats.white);fridge.userData.action="eat";cube(2.7,1.75,-4.25,1.5,1.1,.1,mats.wood);
let tv=cube(1.5,1.15,-4.18,1.8,1.1,.12,mats.dark);tv.userData.action="fun";
let wardrobe=cube(-5.45,1.55,.1,.7,3.1,2.1,mats.wood);wardrobe.userData.action="wardrobe";
let win=cube(.3,2.9,-4.27,2.2,1.5,.06,new THREE.MeshStandardMaterial({color:0x8ec6d6,emissive:0x24495a,emissiveIntensity:.15}));
let bodyCol=state.trait==="techie"?0x34445b:state.trait==="social"?0xd675aa:state.trait==="book"?0x4d83c1:0xe5a34c;let body=cube(.1,1.15,.3,.7,1.05,.42,new THREE.MeshStandardMaterial({color:bodyCol}));let head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,10),mats.skin);head.position.set(.1,2,.3);head.castShadow=true;scene.add(head);cube(-.16,.48,.3,.2,.75,.24,mats.dark);cube(.36,.48,.3,.2,.75,.24,mats.dark);
let interact=[bed,sofa,desk,monitor,kitchen,fridge,tv,wardrobe],ray=new THREE.Raycaster(),mouse=new THREE.Vector2();ren.domElement.addEventListener("pointerup",e=>{let r=ren.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,cam);let hit=ray.intersectObjects(interact)[0];if(!hit)return;let a=hit.object.userData.action;if(a==="coding")train("coding",12000);else if(a==="wardrobe")toast("Wardrobe customization coming next.");else doAction(a)});
let labels=[["🛏️ Sleep",bed],["🍳 Eat",fridge],["💻 Computer",monitor],["🛋️ Relax",sofa],["📺 TV",tv],["👕 Wardrobe",wardrobe]];
function drawLabels(){let layer=q("home3dLabels");if(!layer)return;layer.innerHTML=labels.map(([n,o])=>{let v=o.position.clone();v.y+=1;v.project(cam);return '<span class="home-label" style="left:'+((v.x*.5+.5)*100)+'%;top:'+((-v.y*.5+.5)*100)+'%">'+n+'</span>'}).join("")}
function loop(){if(!host.isConnected)return;ren.render(scene,cam);drawLabels();requestAnimationFrame(loop)}loop()}
function phoneScreen(){let apps=[["💼","Jobs","work"],["🎓","UNN","school"],["🏪","Business","business"],["👥","Contacts","people"],["🏦","Bank","bank"],["🏠","Property","assets"]];return '<section class="phone-wrap"><div class="phone"><div class="phone-top"><span>19:40</span><b>EnuguTel 4G ▰</b></div><h2>'+state.name+'\'s Phone</h2><div class="apps">'+apps.map(a=>'<button onclick="openApp(\''+a[2]+'\')"><i>'+a[0]+'</i><b>'+a[1]+'</b></button>').join("")+'</div><div class="phone-balance">Wallet <b>'+money(state.cash)+'</b></div></div></section>'}
function mapScreen(){return '<section class="map3d-shell"><div class="map3d-title"><b>ENUGU</b><span>Drag to explore • tap a district</span></div><div id="enugu3d"></div><div id="map3dLabels"></div><div class="map3d-zoom"><button onclick="zoom3d(1)">＋</button><button onclick="zoom3d(-1)">−</button></div></section>'}
let map3d=null;
function init3DMap(){let host=q("enugu3d");if(!host)return;if(window.EnuguWorld&&window.EnuguWorld.mountDistrict){window.EnuguWorld.mountDistrict(host,state.place).catch(e=>{console.error(e);host.innerHTML='<div style="padding:24px">World failed to load: '+e.message+'</div>'});return}let ready=()=>{window.removeEventListener("enugu-assets-ready",ready);if(host.isConnected&&window.EnuguWorld)window.EnuguWorld.mountDistrict(host,state.place)};window.addEventListener("enugu-assets-ready",ready,{once:true})}


function buyScreen(){return '<div class="grid">'+card("Buy Mode",'<h2>Build your life</h2><p>Upgrade where you live and what you own.</p>',true)+card("Homes",HOMES.map((h,i)=>row(h.n,money(h.rent)+"/week",state.home===i?'<span class="pill">HOME</span>':'<button onclick="moveHome('+i+')">Move • '+money(h.deposit)+'</button>')).join(""))+card("Transport",state.car?row("Used Corolla","Owned",'<span class="pill">OWNED</span>'):row("Used Corolla",money(6500000),'<button onclick="buyCar()">Buy</button>'))+'</div>'}
window.openApp=function(app){state.tab=app;saveRender()}
function appScreen(){let html='<div class="grid"><button class="back-phone" onclick="state.tab=\'phone\';saveRender()">← Phone</button>';if(state.tab==="work")html+=card("Career",'<p>'+(state.job<0?"You are unemployed.":JOBS[state.job].n)+'</p><button onclick="workShift()">Work a shift</button>',true)+card("Jobs",JOBS.map((j,i)=>row(j.n,money(j.pay)+"/shift • "+j.skill+" Lv "+j.lvl,'<button onclick="applyJob('+i+')">Apply</button>')).join(""));if(state.tab==="school")html+=card("UNN",'<h2>'+(state.graduate?"Graduate 🎓":"Semester "+state.semester+"/8")+'</h2><button onclick="exam()">Sit exams</button>',true)+card("Study",row("Study session","Academics +1",'<button onclick="train(\'academics\',3500)">₦3,500</button>')+row("Coding course","Coding +1",'<button onclick="train(\'coding\',12000)">₦12k</button>'));if(state.tab==="business")html+=card("Your businesses",state.businesses.length?state.businesses.map(i=>row(BUSINESSES[i].n,money(BUSINESSES[i].income)+"/week",'<span class="pill">OWNED</span>')).join(""):"<p>No businesses yet.</p>",true)+card("Opportunities",BUSINESSES.map((b,i)=>row(b.n,money(b.cost),'<button onclick="startBusiness('+i+')">Start</button>')).join(""));if(state.tab==="people")html+=card("Contacts",Object.entries(state.friends).map(([n,v])=>row(n,"Relationship "+v+"/100",'<button onclick="talk(\''+n+'\')">Hang out</button>')).join(""),true);if(state.tab==="assets")html+=buyScreen();if(state.tab==="bank")html+=card("Enugu Bank",'<div class="bankbal"><span>Available balance</span><b>'+money(state.cash)+'</b></div><p>Debt: '+money(state.debt)+'</p>',true);return html+"</div>"}
function render(){q("greeting").textContent="Nnoo, "+state.name+" 👋🏾";q("meta").textContent="Day "+state.day+" • Week "+state.week+" • "+PLACES[state.place].n;q("cash").textContent=money(state.cash);q("footerText").textContent=HOMES[state.home].n+" • Reputation "+state.rep;q("needs").innerHTML=Object.entries(state.needs).map(([k,v])=>'<div class="need">'+k.toUpperCase()+' <b>'+Math.round(v)+'</b><div class="bar"><i style="width:'+v+'%"></i></div></div>').join("");let core=[["home","🏠","Home"],["buy","🛋️","Buy"],["map","🗺️","Map"],["phone","📱","Phone"]];q("nav").innerHTML=core.map(t=>'<button data-tab="'+t[0]+'" class="'+(state.tab===t[0]?"active":"")+'"><i>'+t[1]+'</i><span>'+t[2]+'</span></button>').join("");q("nav").querySelectorAll("button").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.interior=null;saveRender()});if(state.tab==="life")state.tab="home";let html=state.tab==="home"?homeScene():state.tab==="map"?mapScreen():state.tab==="phone"?phoneScreen():state.tab==="buy"?buyScreen():appScreen();q("view").innerHTML=html;if(state.tab==="map")requestAnimationFrame(init3DMap);if(state.tab==="home")requestAnimationFrame(init3DHome)}
function enterGame(){q("onboarding").classList.add("hidden");q("game").classList.remove("hidden");try{render()}catch(e){console.error("Render failed",e);q("view").innerHTML='<section class="card wide"><h2>Loading your life…</h2><p>The 3D scene had a problem, but your game has started.</p></section>'}}
q("traits").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{selectedTrait=b.dataset.trait;q("traits").querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}));
q("startButton").addEventListener("click",()=>{let name=q("nameInput").value.trim();if(!name){q("startError").textContent="Enter your name first.";return}state=newState();state.name=name;state.trait=selectedTrait;state.skills[{hustler:"hustle",techie:"coding",social:"charisma",book:"academics"}[selectedTrait]]++;persist();enterGame();toast("Welcome, "+name+"!")});
q("resetButton").addEventListener("click",()=>{if(confirm("Start a new life?")){localStorage.removeItem("enuguLifeV4");state=newState();q("game").classList.add("hidden");q("onboarding").classList.remove("hidden");q("nameInput").value=""}});
if(state.name)enterGame();
})();