"use strict";
(function(){
const q=id=>document.getElementById(id),money=n=>"₦"+Math.round(n).toLocaleString();
const JOBS=[{n:"Shop Assistant",pay:3000,skill:"hustle",lvl:1},{n:"Junior Developer",pay:7500,skill:"coding",lvl:2},{n:"Bank Officer",pay:6500,skill:"charisma",lvl:2},{n:"Project Manager",pay:16000,skill:"charisma",lvl:5},{n:"Senior Developer",pay:22000,skill:"coding",lvl:6}];
const PLACES=[{n:"Nsukka",fare:0},{n:"Ogbete",fare:2200},{n:"New Haven",fare:2500},{n:"Independence Layout",fare:2800},{n:"Nike",fare:3000}];
const HOMES=[{n:"Campus Lodge",rent:2500,deposit:0},{n:"Nsukka Self-contain",rent:6500,deposit:26000},{n:"Enugu Flat",rent:24000,deposit:96000},{n:"GRA Apartment",rent:85000,deposit:340000}];
const DISTRICTS=[
{tag:"UNN / NSUKKA",venues:[["🎓","UNN Campus","Study, exams & campus life","school"],["🍲","Okpa Spot","Eat and recover hunger","eat"],["🏠","Campus Lodge","Rest at home","sleep"]]},
{tag:"OGBETE",venues:[["🛍️","Ogbete Market","Hustles and business","business"],["🏦","Bank Row","Find career opportunities","work"],["🍛","Food Joint","Grab a meal","eat"]]},
{tag:"NEW HAVEN",venues:[["💻","Tech Hub","Coding and tech careers","work"],["☕","Cafe","Meet people","people"],["🏢","Apartments","Housing options","assets"]]},
{tag:"INDEPENDENCE LAYOUT",venues:[["🏢","Business District","Build your company","business"],["🍽️","Restaurant","Eat and socialise","eat"],["🚗","Auto Dealer","Buy a vehicle","assets"]]},
{tag:"NIKE",venues:[["🌴","Nike Lake","Relax and have fun","fun"],["🏘️","Residential Area","View homes","assets"],["🤝","Hangout","Meet people","people"]]}
];
const BUSINESSES=[{n:"Okpa Stand",cost:45000,income:3500},{n:"Design Studio",cost:180000,income:12000},{n:"Software Agency",cost:650000,income:35000}];
function newState(){return{name:"",trait:"hustler",cash:30000,debt:0,day:1,week:1,place:0,home:0,job:-1,semester:1,graduate:false,rep:0,car:false,px:48,py:70,needs:{hunger:85,energy:90,fun:70,social:65},skills:{hustle:1,coding:1,charisma:1,academics:1},businesses:[],friends:{Ada:10,Emeka:15,Chisom:8},log:["Your story begins in Nsukka."],tab:"home",interior:null}}
let state=newState();try{const old=localStorage.getItem("enuguLifeV4");if(old)state=Object.assign(newState(),JSON.parse(old))}catch(e){state=newState()}
let selectedTrait="hustler";
function persist(){localStorage.setItem("enuguLifeV4",JSON.stringify(state))}
function note(t){state.log.unshift("Day "+state.day+" — "+t);state.log=state.log.slice(0,8)}
function toast(t){q("toast").textContent=t;q("toast").classList.add("show");setTimeout(()=>q("toast").classList.remove("show"),1400)}
function pay(n){if(state.cash<n){toast("Not enough cash.");return false}state.cash-=n;return true}
function nextDay(){state.day++;Object.keys(state.needs).forEach(k=>state.needs[k]=Math.max(0,state.needs[k]-5));if(state.day%7===0){state.week++;let inc=state.businesses.reduce((a,i)=>a+BUSINESSES[i].income,0);state.cash+=inc-HOMES[state.home].rent;note("Weekly income "+money(inc)+" • rent "+money(HOMES[state.home].rent));if(state.cash<0){state.debt+=Math.abs(state.cash);state.cash=0}}}
function saveRender(){persist();render()}
function outfit(){return state.trait==="techie"?"tech":state.trait==="social"?"social":state.trait==="book"?"student":"hustler"}
function world(){let d=DISTRICTS[state.place],v=d.venues;return '<section class="gameworld wide"><div class="worldtop"><b>📍 '+d.tag+'</b><span>Tap anywhere to walk • tap a place to enter</span></div><div id="playfield" class="playfield district-'+state.place+'"><div class="road road-h"></div><div class="road road-v"></div><div class="crosswalk"></div><div class="tree t1">🌳</div><div class="tree t2">🌴</div><div class="tree t3">🌳</div>'+v.map((x,i)=>'<button class="map-building mb'+(i+1)+'" data-venue="'+i+'"><span class="roof"></span><span class="front"><i></i><i></i><em></em></span><strong>'+x[0]+' '+x[1]+'</strong></button>').join("")+'<button class="map-npc npc-a" data-person="Ada"><span>👩🏾</span><b>Ada</b></button><button class="map-npc npc-e" data-person="Emeka"><span>👨🏾</span><b>Emeka</b></button><button class="map-npc npc-c" data-person="Chisom"><span>🧑🏾</span><b>Chisom</b></button><div id="playerSprite" class="player-sprite '+outfit()+'" style="left:'+(state.px||48)+'%;top:'+(state.py||70)+'%"><span class="hair"></span><span class="face"></span><span class="shirt"></span><span class="legs"></span><b>'+state.name+'</b></div><div class="traffic">🛺</div></div></section>'}
function interior(){if(state.interior===null)return "";let v=DISTRICTS[state.place].venues[state.interior],label=v[3]==="eat"?"🍲 Buy meal":v[3]==="sleep"?"😴 Rest":v[3]==="fun"?"✨ Relax":"Continue →";return '<section class="roomscene wide"><div class="room-back"><div class="room-sign">'+v[0]+' '+v[1]+'</div><div class="room-window"></div><div class="room-counter"></div><div class="room-player '+outfit()+'"><span class="hair"></span><span class="face"></span><span class="shirt"></span><span class="legs"></span></div><div class="room-actions"><button onclick="venueAction()">'+label+'</button><button onclick="leaveVenue()">← Go outside</button></div></div></section>'}
function bindWorld(){let f=q("playfield");if(!f)return;f.addEventListener("click",e=>{if(e.target.closest(".map-building,.map-npc"))return;let r=f.getBoundingClientRect();state.px=Math.max(4,Math.min(92,(e.clientX-r.left)/r.width*100));state.py=Math.max(15,Math.min(84,(e.clientY-r.top)/r.height*100));persist();let p=q("playerSprite");p.style.left=state.px+"%";p.style.top=state.py+"%"});f.querySelectorAll(".map-building").forEach(x=>x.addEventListener("click",()=>enterVenue(Number(x.dataset.venue))));f.querySelectorAll(".map-npc").forEach(x=>x.addEventListener("click",()=>talk(x.dataset.person)))} 
function row(a,b,c){return '<div class="row"><div><b>'+a+'</b><p>'+b+'</p></div>'+c+'</div>'}
function card(t,b,wide){return '<section class="card '+(wide?"wide":"")+'"><h3>'+t+'</h3>'+b+'</section>'}
window.enterVenue=function(i){state.interior=i;note("Entered "+DISTRICTS[state.place].venues[i][1]+".");saveRender()};window.leaveVenue=function(){state.interior=null;saveRender()};window.venueAction=function(){let v=DISTRICTS[state.place].venues[state.interior],a=v[3];if(a==="eat"||a==="sleep"||a==="fun"){doAction(a);return}state.interior=null;state.tab=a;saveRender()};window.visitVenue=window.enterVenue;
window.doAction=function(a){if(a==="eat"){if(!pay(900))return;state.needs.hunger=Math.min(100,state.needs.hunger+35);note("Ate a good meal.")}else if(a==="sleep"){state.needs.energy=100;note("Slept and recovered.")}else if(a==="gig"){let p=2200+state.skills.hustle*700+(state.trait==="hustler"?1000:0);state.cash+=p;state.skills.hustle=Math.min(10,state.skills.hustle+.2);note("Side hustle paid "+money(p))}else if(a==="fun"){if(!pay(2000))return;state.needs.fun=Math.min(100,state.needs.fun+35);state.needs.social=Math.min(100,state.needs.social+20);note("Went out with friends.")}nextDay();saveRender()};
window.applyJob=function(i){let j=JOBS[i];if(state.skills[j.skill]<j.lvl){toast(j.skill+" level "+j.lvl+" required.");return}state.job=i;note("Got a job as "+j.n+".");saveRender()};
window.workShift=function(){if(state.job<0){toast("Get a job first.");return}if(state.needs.energy<20){toast("You need rest.");return}let j=JOBS[state.job];state.cash+=j.pay;state.needs.energy=Math.max(0,state.needs.energy-20);state.skills[j.skill]=Math.min(10,state.skills[j.skill]+.2);state.rep++;note("Worked as "+j.n+" and earned "+money(j.pay));nextDay();saveRender()};
window.train=function(k,c){if(!pay(c))return;let bonus=(state.trait==="techie"&&k==="coding")||(state.trait==="book"&&k==="academics")?.5:0;state.skills[k]=Math.min(10,state.skills[k]+1+bonus);note("Improved "+k+".");nextDay();saveRender()};
window.exam=function(){if(state.graduate){toast("Already graduated 🎓");return}if(state.skills.academics<state.semester){toast("Study more first.");return}let c=12000+state.semester*3000;if(!pay(c))return;state.semester++;if(state.semester>8){state.semester=8;state.graduate=true;note("Graduated from UNN 🎓")}else note("Passed exams. Semester "+state.semester);nextDay();saveRender()};
window.travel=function(i){state.interior=null;let fare=state.car?Math.floor(PLACES[i].fare*.4):PLACES[i].fare;if(!pay(fare))return;state.place=i;note("Travelled to "+PLACES[i].n+".");nextDay();saveRender()};
window.startBusiness=function(i){if(state.businesses.includes(i)){toast("Already owned.");return}if(!pay(BUSINESSES[i].cost))return;state.businesses.push(i);state.rep+=2;note("Opened "+BUSINESSES[i].n+".");saveRender()};
window.moveHome=function(i){if(!pay(HOMES[i].deposit))return;state.home=i;note("Moved into "+HOMES[i].n+".");saveRender()};
window.buyCar=function(){if(state.car){toast("You already own a car.");return}if(!pay(6500000))return;state.car=true;state.rep+=5;note("Bought a used Corolla.");saveRender()};
window.talk=function(n){if(!pay(1000))return;state.friends[n]=Math.min(100,state.friends[n]+10+(state.trait==="social"?5:0));state.needs.social=Math.min(100,state.needs.social+20);note("Spent time with "+n+".");nextDay();saveRender()};
function sim(){return '<div class="sim '+outfit()+'"><span class="simhair"></span><span class="simface"></span><span class="simbody"></span><span class="simlegs"></span></div>'}
function homeScene(){return '<section class="home-scene"><div class="home-title"><b>'+HOMES[state.home].n+'</b><span>Home • '+PLACES[state.place].n+'</span></div><button class="furniture bed" onclick="doAction(\'sleep\')"><span>🛏️</span><b>Sleep</b></button><button class="furniture kitchen" onclick="doAction(\'eat\')"><span>🍳</span><b>Cook / Eat</b></button><button class="furniture sofa" onclick="doAction(\'fun\')"><span>🛋️</span><b>Relax</b></button><button class="furniture desk" onclick="train(\'coding\',12000)"><span>💻</span><b>Computer</b></button><div class="home-sim">'+sim()+'<strong>'+state.name+'</strong></div></section>'}
function phoneScreen(){let apps=[["💼","Jobs","work"],["🎓","UNN","school"],["🏪","Business","business"],["👥","Contacts","people"],["🏦","Bank","bank"],["🏠","Property","assets"]];return '<section class="phone-wrap"><div class="phone"><div class="phone-top"><span>19:40</span><b>EnuguTel 4G ▰</b></div><h2>'+state.name+'\'s Phone</h2><div class="apps">'+apps.map(a=>'<button onclick="openApp(\''+a[2]+'\')"><i>'+a[0]+'</i><b>'+a[1]+'</b></button>').join("")+'</div><div class="phone-balance">Wallet <b>'+money(state.cash)+'</b></div></div></section>'}
function mapScreen(){return '<section class="city-map"><div class="map-head"><b>Enugu & Nsukka</b><span>Choose a destination</span></div><div class="map-road mr1"></div><div class="map-road mr2"></div>'+PLACES.map((p,i)=>'<button class="destination d'+i+' '+(state.place===i?"here":"")+'" onclick="travel('+i+')"><span>'+["🎓","🛍️","☕","🏢","🌴"][i]+'</span><b>'+p.n+'</b><small>'+(i===state.place?"YOU ARE HERE":money(p.fare))+'</small></button>').join("")+'<div class="map-water"></div></section>'}
function buyScreen(){return '<div class="grid">'+card("Buy Mode",'<h2>Build your life</h2><p>Upgrade where you live and what you own.</p>',true)+card("Homes",HOMES.map((h,i)=>row(h.n,money(h.rent)+"/week",state.home===i?'<span class="pill">HOME</span>':'<button onclick="moveHome('+i+')">Move • '+money(h.deposit)+'</button>')).join(""))+card("Transport",state.car?row("Used Corolla","Owned",'<span class="pill">OWNED</span>'):row("Used Corolla",money(6500000),'<button onclick="buyCar()">Buy</button>'))+'</div>'}
window.openApp=function(app){state.tab=app;saveRender()}
function appScreen(){let html='<div class="grid"><button class="back-phone" onclick="state.tab=\'phone\';saveRender()">← Phone</button>';if(state.tab==="work")html+=card("Career",'<p>'+(state.job<0?"You are unemployed.":JOBS[state.job].n)+'</p><button onclick="workShift()">Work a shift</button>',true)+card("Jobs",JOBS.map((j,i)=>row(j.n,money(j.pay)+"/shift • "+j.skill+" Lv "+j.lvl,'<button onclick="applyJob('+i+')">Apply</button>')).join(""));if(state.tab==="school")html+=card("UNN",'<h2>'+(state.graduate?"Graduate 🎓":"Semester "+state.semester+"/8")+'</h2><button onclick="exam()">Sit exams</button>',true)+card("Study",row("Study session","Academics +1",'<button onclick="train(\'academics\',3500)">₦3,500</button>')+row("Coding course","Coding +1",'<button onclick="train(\'coding\',12000)">₦12k</button>'));if(state.tab==="business")html+=card("Your businesses",state.businesses.length?state.businesses.map(i=>row(BUSINESSES[i].n,money(BUSINESSES[i].income)+"/week",'<span class="pill">OWNED</span>')).join(""):"<p>No businesses yet.</p>",true)+card("Opportunities",BUSINESSES.map((b,i)=>row(b.n,money(b.cost),'<button onclick="startBusiness('+i+')">Start</button>')).join(""));if(state.tab==="people")html+=card("Contacts",Object.entries(state.friends).map(([n,v])=>row(n,"Relationship "+v+"/100",'<button onclick="talk(\''+n+'\')">Hang out</button>')).join(""),true);if(state.tab==="assets")html+=buyScreen();if(state.tab==="bank")html+=card("Enugu Bank",'<div class="bankbal"><span>Available balance</span><b>'+money(state.cash)+'</b></div><p>Debt: '+money(state.debt)+'</p>',true);return html+"</div>"}
function render(){q("greeting").textContent="Nnoo, "+state.name+" 👋🏾";q("meta").textContent="Day "+state.day+" • Week "+state.week+" • "+PLACES[state.place].n;q("cash").textContent=money(state.cash);q("footerText").textContent=HOMES[state.home].n+" • Reputation "+state.rep;q("needs").innerHTML=Object.entries(state.needs).map(([k,v])=>'<div class="need">'+k.toUpperCase()+' <b>'+Math.round(v)+'</b><div class="bar"><i style="width:'+v+'%"></i></div></div>').join("");let core=[["home","🏠","Home"],["buy","🛋️","Buy"],["map","🗺️","Map"],["phone","📱","Phone"]];q("nav").innerHTML=core.map(t=>'<button data-tab="'+t[0]+'" class="'+(state.tab===t[0]?"active":"")+'"><i>'+t[1]+'</i><span>'+t[2]+'</span></button>').join("");q("nav").querySelectorAll("button").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.interior=null;saveRender()});if(state.tab==="life")state.tab="home";let html=state.tab==="home"?homeScene():state.tab==="map"?mapScreen():state.tab==="phone"?phoneScreen():state.tab==="buy"?buyScreen():appScreen();q("view").innerHTML=html}
function enterGame(){q("onboarding").classList.add("hidden");q("game").classList.remove("hidden");render()}
q("traits").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{selectedTrait=b.dataset.trait;q("traits").querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}));
q("startButton").addEventListener("click",()=>{let name=q("nameInput").value.trim();if(!name){q("startError").textContent="Enter your name first.";return}state=newState();state.name=name;state.trait=selectedTrait;state.skills[{hustler:"hustle",techie:"coding",social:"charisma",book:"academics"}[selectedTrait]]++;persist();enterGame();toast("Welcome, "+name+"!")});
q("resetButton").addEventListener("click",()=>{if(confirm("Start a new life?")){localStorage.removeItem("enuguLifeV4");state=newState();q("game").classList.add("hidden");q("onboarding").classList.remove("hidden");q("nameInput").value=""}});
if(state.name)enterGame();
})();