import * as THREE from "three";import {loadGLB,optimize,CharacterController} from "./assetRuntime.js";
const A="assets/models/";
const pieces=[
["furniture/bedSingle.glb",[-2.15,0,-1.55],0,1,"sleep"],["furniture/desk.glb",[-2.2,0,1.35],Math.PI,1,"coding"],["furniture/chairDesk.glb",[-1.95,0,.65],0,1],["furniture/laptop.glb",[-2.2,.82,1.3],Math.PI,1,"coding"],["furniture/kitchenFridge.glb",[2.45,0,-1.65],0,1,"eat"],["furniture/kitchenStove.glb",[1.55,0,-1.65],0,1,"eat"],["furniture/loungeSofa.glb",[1.65,0,1.45],Math.PI,1,"fun"],["furniture/cabinetTelevision.glb",[.65,0,-2.25],0,1,"fun"],["furniture/bookcaseClosed.glb",[-3.05,0,-.15],Math.PI/2,1,"wardrobe"],["furniture/lampRoundFloor.glb",[2.75,0,1.65],0,1],["furniture/plantSmall2.glb",[2.85,0,2.15],0,1]];
async function add(scene,url,pos,rot=0,scale=1,action){try{let g=await loadGLB(A+url),o=optimize(g.scene.clone(true));o.position.set(...pos);o.rotation.y=rot;o.scale.setScalar(scale);if(action){o.userData.action=action;o.traverse(x=>x.userData.action=action)}scene.add(o);return o}catch(e){console.warn("Asset missing",url);return null}}
export async function mountCampusLodge(host,handlers={}){let scene=new THREE.Scene();scene.background=new THREE.Color(0xc8c1b3);let w=host.clientWidth,h=host.clientHeight,cam=new THREE.PerspectiveCamera(46,w/h,.1,100);cam.position.set(5.4,3.8,6.4);cam.lookAt(0,.85,0);let ren=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});ren.setPixelRatio(Math.min(devicePixelRatio,2));ren.setSize(w,h);ren.outputColorSpace=THREE.SRGBColorSpace;ren.toneMapping=THREE.ACESFilmicToneMapping;ren.toneMappingExposure=1.12;ren.shadowMap.enabled=true;ren.shadowMap.type=THREE.PCFSoftShadowMap;host.innerHTML="";host.appendChild(ren.domElement);scene.add(new THREE.HemisphereLight(0xfff6e6,0x554b40,1.7));let sun=new THREE.DirectionalLight(0xffe0b5,3.2);sun.position.set(-4,7,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-6;sun.shadow.camera.right=6;sun.shadow.camera.top=6;sun.shadow.camera.bottom=-6;scene.add(sun);let fill=new THREE.PointLight(0xffd7a0,14,9,2);fill.position.set(1.5,2.8,1.5);scene.add(fill);
let floor=new THREE.Mesh(new THREE.PlaneGeometry(7,5.4),new THREE.MeshStandardMaterial({color:0x8a6b50,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);let wallMat=new THREE.MeshStandardMaterial({color:0xe6dac7,roughness:1});[[-3.5,1.8,0,.12,3.6,5.4],[0,1.8,-2.7,7,3.6,.12]].forEach(v=>{let m=new THREE.Mesh(new THREE.BoxGeometry(v[3],v[4],v[5]),wallMat);m.position.set(v[0],v[1],v[2]);m.receiveShadow=true;scene.add(m)});
let targets=[];for(const p of pieces){let o=await add(scene,...p);if(o&&p[4]){o.traverse(x=>{if(x.isMesh)targets.push(x)})}}
let player=null,controller=null;try{let g=await loadGLB(A+"characters/player.glb");player=optimize(g.scene.clone(true));player.position.set(0,0,.35);player.rotation.y=-.35;player.scale.setScalar(1.45);scene.add(player);controller=new CharacterController(player,g.animations)}catch(e){console.warn("Player model missing")}
let keys={},move=new THREE.Vector3(),camTarget=new THREE.Vector3(),camPos=new THREE.Vector3(),nearest=null;
const actionLabels={sleep:"Sleep",coding:"Use laptop",eat:"Eat / cook",fun:"Relax",wardrobe:"Change clothes"};
window.addEventListener("keydown",e=>{keys[e.code]=true;if(e.code==="KeyE"&&nearest){controller?.play(nearest.action);handlers[nearest.action]?.()}});
window.addEventListener("keyup",e=>keys[e.code]=false);
let prompt=document.createElement("div");prompt.style.cssText="position:absolute;left:50%;bottom:22px;transform:translateX(-50%);z-index:8;padding:9px 13px;border-radius:12px;background:rgba(7,21,13,.88);color:white;font:700 12px system-ui;display:none;pointer-events:none;backdrop-filter:blur(8px)";host.style.position="relative";host.appendChild(prompt);
let zones=pieces.filter(p=>p[4]).map(p=>({pos:new THREE.Vector3(p[1][0],0,p[1][2]),action:p[4]}));
function updatePlayer(dt){
 if(!player)return;
 let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),z=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);
 move.set(x,0,z);let moving=move.lengthSq()>0;
 if(moving){move.normalize();let sprint=!!(keys.ShiftLeft||keys.ShiftRight),speed=sprint?2.7:1.65;player.position.addScaledVector(move,speed*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-2.75,2.75);player.position.z=THREE.MathUtils.clamp(player.position.z,-2.05,2.05);player.rotation.y=Math.atan2(move.x,move.z);controller?.play(sprint?"sprint":"walk")}else controller?.play("idle");
 nearest=null;let best=1.15;for(let z of zones){let d=player.position.distanceTo(z.pos);if(d<best){best=d;nearest=z}}
 if(nearest){prompt.textContent="E  •  "+actionLabels[nearest.action];prompt.style.display="block"}else prompt.style.display="none";
 let forward=new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y));camTarget.set(player.position.x,player.position.y+1.15,player.position.z);camPos.copy(camTarget).addScaledVector(forward,-3.2);camPos.y+=1.65;cam.position.lerp(camPos,1-Math.pow(.001,dt));let look=camTarget.clone().addScaledVector(forward,.8);cam.lookAt(look);
}
let ray=new THREE.Raycaster(),mouse=new THREE.Vector2();function interactAt(x,y){let r=ren.domElement.getBoundingClientRect();mouse.set((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1);ray.setFromCamera(mouse,cam);let hit=ray.intersectObjects(targets,false)[0];if(!hit)return;let o=hit.object;while(o&&!o.userData.action)o=o.parent;let a=o?.userData.action;if(a){controller?.play(a);handlers[a]?.()}}
let down=null;ren.domElement.style.touchAction="manipulation";ren.domElement.style.cursor="pointer";
ren.domElement.addEventListener("pointerdown",e=>{down={x:e.clientX,y:e.clientY}});
ren.domElement.addEventListener("pointerup",e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)<12)interactAt(e.clientX,e.clientY);down=null});
ren.domElement.addEventListener("pointercancel",()=>down=null);
let mobile=document.createElement("div");mobile.innerHTML='<div style="position:absolute;left:18px;bottom:18px;z-index:9;display:grid;grid-template-columns:44px 44px 44px;gap:4px"><span></span><button data-k="KeyW">▲</button><span></span><button data-k="KeyA">◀</button><button data-k="KeyS">▼</button><button data-k="KeyD">▶</button></div><button data-use="1" style="position:absolute;right:20px;bottom:28px;z-index:9;width:58px;height:58px;border-radius:50%;font-weight:900">USE</button>';host.appendChild(mobile);mobile.querySelectorAll("[data-k]").forEach(b=>{let k=b.dataset.k;b.addEventListener("pointerdown",e=>{e.preventDefault();keys[k]=true});["pointerup","pointercancel","pointerleave"].forEach(n=>b.addEventListener(n,()=>keys[k]=false))});mobile.querySelector("[data-use]").onclick=()=>{if(nearest){controller?.play(nearest.action);handlers[nearest.action]?.()}};
let ro=new ResizeObserver(()=>{if(!host.isConnected)return;let nw=host.clientWidth,nh=host.clientHeight;if(!nw||!nh)return;cam.aspect=nw/nh;cam.updateProjectionMatrix();ren.setSize(nw,nh,false)});ro.observe(host);let clock=new THREE.Clock();function loop(){if(!host.isConnected){ro.disconnect();ren.dispose();return}let dt=Math.min(clock.getDelta(),.05);updatePlayer(dt);controller?.update(dt);ren.render(scene,cam);requestAnimationFrame(loop)}loop();return{scene,cam,renderer:ren,player,controller}}
window.EnuguCampus={mountCampusLodge};