import * as THREE from "three";import {loadGLB,optimize,CharacterController} from "./assetRuntime.js";
const A="assets/models/";
const pieces=[
["furniture/bedSingle.glb",[-3,0,-2.5],0,1,"sleep"],["furniture/desk.glb",[-3,0,2.1],Math.PI,1,"coding"],["furniture/chairDesk.glb",[-2.6,0,1.25],0,1],["furniture/laptop.glb",[-3,.82,2.05],Math.PI,1,"coding"],["furniture/kitchenFridge.glb",[3.6,0,-2.8],0,1,"eat"],["furniture/kitchenStove.glb",[2.4,0,-2.8],0,1,"eat"],["furniture/loungeSofa.glb",[2.5,0,2.2],Math.PI,1,"fun"],["furniture/cabinetTelevision.glb",[1.5,0,-3.6],0,1,"fun"],["furniture/bookcaseClosed.glb",[-4.4,0,.1],Math.PI/2,1,"wardrobe"],["furniture/lampRoundFloor.glb",[4,0,2.4],0,1],["furniture/plantSmall2.glb",[4.3,0,3],0,1]];
async function add(scene,url,pos,rot=0,scale=1,action){try{let g=await loadGLB(A+url),o=optimize(g.scene.clone(true));o.position.set(...pos);o.rotation.y=rot;o.scale.setScalar(scale);if(action){o.userData.action=action;o.traverse(x=>x.userData.action=action)}scene.add(o);return o}catch(e){console.warn("Asset missing",url);return null}}
export async function mountCampusLodge(host,handlers={}){let scene=new THREE.Scene();scene.background=new THREE.Color(0xc9c0ad);let w=host.clientWidth,h=host.clientHeight,cam=new THREE.PerspectiveCamera(40,w/h,.1,100);cam.position.set(7,6,9);cam.lookAt(0,1,0);let ren=new THREE.WebGLRenderer({antialias:true,powerPreference:"low-power"});ren.setPixelRatio(Math.min(devicePixelRatio,1.5));ren.setSize(w,h);ren.shadowMap.enabled=true;host.innerHTML="";host.appendChild(ren.domElement);scene.add(new THREE.HemisphereLight(0xfff5df,0x62594e,2.5));let sun=new THREE.DirectionalLight(0xffdfaa,3);sun.position.set(-5,10,7);sun.castShadow=true;scene.add(sun);
let floor=new THREE.Mesh(new THREE.PlaneGeometry(10,8),new THREE.MeshStandardMaterial({color:0x8a6b50,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);let wallMat=new THREE.MeshStandardMaterial({color:0xe6dac7,roughness:1});[[-5,2,0,.15,4,8],[0,2,-4,10,4,.15]].forEach(v=>{let m=new THREE.Mesh(new THREE.BoxGeometry(v[3],v[4],v[5]),wallMat);m.position.set(v[0],v[1],v[2]);m.receiveShadow=true;scene.add(m)});
let targets=[];for(const p of pieces){let o=await add(scene,...p);if(o&&p[4])targets.push(o)}
let player=null,controller=null;try{let g=await loadGLB(A+"characters/player.glb");player=optimize(g.scene.clone(true));player.position.set(0,0,.4);player.scale.setScalar(1);scene.add(player);controller=new CharacterController(player,g.animations)}catch(e){console.warn("Player model missing")}
let ray=new THREE.Raycaster(),mouse=new THREE.Vector2();ren.domElement.addEventListener("pointerup",e=>{let r=ren.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,cam);let hit=ray.intersectObjects(targets,true)[0];if(!hit)return;let o=hit.object;while(o&&!o.userData.action)o=o.parent;let a=o?.userData.action;if(a){controller?.play(a);handlers[a]?.()}});
let clock=new THREE.Clock();function loop(){if(!host.isConnected){ren.dispose();return}controller?.update(clock.getDelta());ren.render(scene,cam);requestAnimationFrame(loop)}loop();return{scene,cam,renderer:ren,player,controller}}
window.EnuguCampus={mountCampusLodge};