import * as THREE from "three";import {loadGLB,optimize,CharacterController} from "./assetRuntime.js";
const A="assets/models/",NAMES=["Nsukka / UNN","GRA","Trans-Ekulu","Abakpa Nike","Emene","New Haven","Ogui / Asata","Ogbete","Independence Layout","Thinkers Corner","Uwani","Achara Layout","Nike Lake"];
const themes=[["UNN Campus",0x73945a],["Quiet GRA",0x658a5b],["Trans-Ekulu",0x6f955f],["Abakpa",0x7c9258],["Emene",0x78945e],["New Haven",0x658b62],["Ogui",0x718c55],["Ogbete Market",0x81904e],["Independence",0x62895c],["Thinkers Corner",0x6b915e],["Uwani",0x77905a],["Achara",0x7a8c57],["Nike Lake",0x5c9668]];
async function clone(url){let g=await loadGLB(A+url);return optimize(g.scene.clone(true))}
export async function mountDistrict(host,index=0,handlers={}){host.innerHTML="";host.style.position="relative";let scene=new THREE.Scene();scene.background=new THREE.Color(0x93c7df);scene.fog=new THREE.Fog(0x93c7df,18,42);let w=host.clientWidth,h=host.clientHeight,cam=new THREE.PerspectiveCamera(58,w/h,.1,80),ren=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});ren.setPixelRatio(Math.min(devicePixelRatio,1.7));ren.setSize(w,h);ren.outputColorSpace=THREE.SRGBColorSpace;ren.toneMapping=THREE.ACESFilmicToneMapping;ren.toneMappingExposure=1.05;ren.shadowMap.enabled=true;ren.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(ren.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x52634b,1.8));let sun=new THREE.DirectionalLight(0xffe2b5,3);sun.position.set(-8,14,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
let ground=new THREE.Mesh(new THREE.PlaneGeometry(34,34),new THREE.MeshStandardMaterial({color:themes[index][1],roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
let roadMat=new THREE.MeshStandardMaterial({color:0x565957,roughness:1});for(let [x,z,sx,sz] of [[0,0,5,34],[-9,3,12,4],[9,-5,12,4]]){let m=new THREE.Mesh(new THREE.PlaneGeometry(sx,sz),roadMat);m.rotation.x=-Math.PI/2;m.position.set(x,.012,z);scene.add(m)}
let buildingFiles=["building-type-a.glb","building-type-f.glb","building-type-k.glb"],spots=[[-11,-11],[-7,-11],[7,-11],[11,-11],[-12,9],[-8,9],[8,9],[12,9],[-11,-1],[11,1]];for(let i=0;i<spots.length;i++){try{let o=await clone("enugu/"+buildingFiles[(i+index)%3]);o.position.set(spots[i][0]+((index%3)-1)*.35,0,spots[i][1]);o.rotation.y=spots[i][1]>0?Math.PI:0;o.scale.setScalar(.8+(i%3)*.08);scene.add(o)}catch(e){}}
for(let i=0;i<18;i++){try{let t=await clone("enugu/"+(i%3?"tree-small.glb":"tree-large.glb"));let a=i*.91+index*.33,r=12+(i%4);t.position.set(Math.sin(a)*r,0,Math.cos(a)*r);t.scale.setScalar(.8+(i%2)*.3);scene.add(t)}catch(e){}}
if(index===12){let lake=new THREE.Mesh(new THREE.CircleGeometry(7,32),new THREE.MeshStandardMaterial({color:0x4e9db7,roughness:.35,metalness:.05}));lake.rotation.x=-Math.PI/2;lake.position.set(9,.025,7);scene.add(lake)}
let player,controller;try{let g=await loadGLB(A+"characters/player.glb");player=optimize(g.scene.clone(true));player.scale.setScalar(1.45);player.position.set(0,0,7);scene.add(player);controller=new CharacterController(player,g.animations)}catch(e){}
let title=document.createElement("div");title.style.cssText="position:absolute;left:14px;top:14px;z-index:4;background:rgba(5,20,12,.86);color:white;padding:10px 13px;border-radius:12px;font:700 13px system-ui";title.textContent=NAMES[index]+" • WASD to explore";host.appendChild(title);
let keys={};window.addEventListener("keydown",e=>keys[e.code]=true);window.addEventListener("keyup",e=>keys[e.code]=false);let clock=new THREE.Clock(),v=new THREE.Vector3(),target=new THREE.Vector3(),cp=new THREE.Vector3();
function loop(){if(!host.isConnected){ren.dispose();return}let dt=Math.min(clock.getDelta(),.05),x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),z=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);if(player){v.set(x,0,z);if(v.lengthSq()){v.normalize();let sprint=keys.ShiftLeft||keys.ShiftRight;player.position.addScaledVector(v,(sprint?4:2.3)*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-15,15);player.position.z=THREE.MathUtils.clamp(player.position.z,-15,15);player.rotation.y=Math.atan2(v.x,v.z);controller?.play(sprint?"sprint":"walk")}else controller?.play("idle");let f=new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y));target.set(player.position.x,player.position.y+1.2,player.position.z);cp.copy(target).addScaledVector(f,-4.2);cp.y+=2;cam.position.lerp(cp,1-Math.pow(.002,dt));cam.lookAt(target.clone().addScaledVector(f,1.5));controller?.update(dt)}ren.render(scene,cam);requestAnimationFrame(loop)}loop();let ro=new ResizeObserver(()=>{let W=host.clientWidth,H=host.clientHeight;if(W&&H){cam.aspect=W/H;cam.updateProjectionMatrix();ren.setSize(W,H,false)}});ro.observe(host);return{scene,player,controller}}
window.EnuguWorld={mountDistrict};