import * as THREE from "three";import {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";
const loader=new GLTFLoader(),cache=new Map(),A="assets/models/";
async function model(path){if(!cache.has(path))cache.set(path,new Promise((res,rej)=>loader.load(A+path,res,undefined,rej)));return cache.get(path)}
function prep(o){o.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true}});return o}
export class EnuguGame3D{
 constructor(host){this.host=host;this.keys={};this.mix=null;this.actions={};this.current=null;this.player=null;this.alive=true;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x9ccbe0);let w=host.clientWidth||800,h=host.clientHeight||520;this.camera=new THREE.PerspectiveCamera(58,w/h,.1,100);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.setSize(w,h);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.shadowMap.enabled=true;host.innerHTML="";host.appendChild(this.renderer.domElement);this.down=e=>this.keys[e.code]=true;this.up=e=>this.keys[e.code]=false;window.addEventListener("keydown",this.down);window.addEventListener("keyup",this.up);this.clock=new THREE.Clock();this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(host)}
 light(){this.scene.add(new THREE.HemisphereLight(0xffffff,0x53634c,1.9));let s=new THREE.DirectionalLight(0xffe4bd,3);s.position.set(-8,14,9);s.castShadow=true;s.shadow.mapSize.set(2048,2048);this.scene.add(s)}
 async add(path,pos=[0,0,0],rot=0,scale=1){try{let g=await model(path),o=prep(g.scene.clone(true));o.position.set(...pos);o.rotation.y=rot;o.scale.setScalar(scale);this.scene.add(o);return o}catch(e){console.warn("asset",path,e);return null}}
 async character(pos=[0,0,6]){let g=await model("characters/player.glb"),o=prep(g.scene.clone(true));o.position.set(...pos);o.scale.setScalar(1.45);this.scene.add(o);this.player=o;this.mix=new THREE.AnimationMixer(o);for(let clip of g.animations){let a=this.mix.clipAction(clip);this.actions[clip.name.toLowerCase()]=a}this.play("idle")}
 play(n){let a=this.actions[n]||this.actions[n==="sprint"?"run":"idle"];if(!a||a===this.current)return;if(this.current)this.current.fadeOut(.15);a.reset().fadeIn(.15).play();this.current=a}
 movement(dt){if(!this.player)return;let x=(this.keys.KeyD||this.keys.ArrowRight?1:0)-(this.keys.KeyA||this.keys.ArrowLeft?1:0),z=(this.keys.KeyS||this.keys.ArrowDown?1:0)-(this.keys.KeyW||this.keys.ArrowUp?1:0),v=new THREE.Vector3(x,0,z);if(v.lengthSq()){v.normalize();let sprint=this.keys.ShiftLeft||this.keys.ShiftRight;this.player.position.addScaledVector(v,(sprint?4:2.2)*dt);this.player.position.x=THREE.MathUtils.clamp(this.player.position.x,-15,15);this.player.position.z=THREE.MathUtils.clamp(this.player.position.z,-15,15);this.player.rotation.y=Math.atan2(v.x,v.z);this.play(sprint?"sprint":"walk")}else this.play("idle");let f=new THREE.Vector3(Math.sin(this.player.rotation.y),0,Math.cos(this.player.rotation.y)),look=this.player.position.clone().add(new THREE.Vector3(0,1.2,0)),want=look.clone().addScaledVector(f,-4.2);want.y+=2;this.camera.position.lerp(want,1-Math.pow(.002,dt));this.camera.lookAt(look.clone().addScaledVector(f,1.2))}
 start(){const tick=()=>{if(!this.alive||!this.host.isConnected)return this.destroy();let dt=Math.min(this.clock.getDelta(),.05);this.movement(dt);this.mix?.update(dt);this.renderer.render(this.scene,this.camera);requestAnimationFrame(tick)};tick()}
 resize(){let w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 destroy(){if(!this.alive)return;this.alive=false;window.removeEventListener("keydown",this.down);window.removeEventListener("keyup",this.up);this.ro.disconnect();this.renderer.dispose()}
}
const districts=["Nsukka / UNN","GRA","Trans-Ekulu","Abakpa Nike","Emene","New Haven","Ogui / Asata","Ogbete","Independence Layout","Thinkers Corner","Uwani","Achara Layout","Nike Lake"];
export async function mountWorld(host,index=0){let g=new EnuguGame3D(host);g.light();let ground=new THREE.Mesh(new THREE.PlaneGeometry(34,34),new THREE.MeshStandardMaterial({color:index===12?0x65976a:0x76945d,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;g.scene.add(ground);for(let [x,z,sx,sz] of [[0,0,5,34],[-9,3,12,4],[9,-5,12,4]]){let r=new THREE.Mesh(new THREE.PlaneGeometry(sx,sz),new THREE.MeshStandardMaterial({color:0x555957,roughness:1}));r.rotation.x=-Math.PI/2;r.position.set(x,.02,z);g.scene.add(r)}let files=["building-type-a.glb","building-type-f.glb","building-type-k.glb"],spots=[[-11,-11],[-7,-11],[7,-11],[11,-11],[-12,9],[-8,9],[8,9],[12,9],[-11,-1],[11,1]];for(let i=0;i<spots.length;i++)await g.add("enugu/"+files[(i+index)%3],[spots[i][0],0,spots[i][1]],spots[i][1]>0?Math.PI:0,.9);if(index===12){let water=new THREE.Mesh(new THREE.CircleGeometry(7,32),new THREE.MeshStandardMaterial({color:0x4b9ebc,roughness:.3}));water.rotation.x=-Math.PI/2;water.position.set(9,.03,7);g.scene.add(water)}await g.character();let badge=document.createElement("div");badge.className="world-badge";badge.textContent=districts[index]+" • WASD / arrows • Shift to run";host.appendChild(badge);g.start();return g}
export async function mountHome(host){let g=new EnuguGame3D(host);g.scene.background=new THREE.Color(0xc8c1b3);g.light();let floor=new THREE.Mesh(new THREE.PlaneGeometry(7,5.4),new THREE.MeshStandardMaterial({color:0x8a6b50,roughness:1}));floor.rotation.x=-Math.PI/2;g.scene.add(floor);let items=[["furniture/bedSingle.glb",[-2.1,0,-1.5],0],["furniture/desk.glb",[-2.1,0,1.3],Math.PI],["furniture/chairDesk.glb",[-1.8,0,.6],0],["furniture/kitchenFridge.glb",[2.4,0,-1.6],0],["furniture/kitchenStove.glb",[1.5,0,-1.6],0],["furniture/loungeSofa.glb",[1.5,0,1.4],Math.PI],["furniture/cabinetTelevision.glb",[.5,0,-2.2],0]];for(let i of items)await g.add(i[0],i[1],i[2]);await g.character([0,0,.3]);g.start();return g}
window.Enugu3D={mountWorld,mountHome};